# Generated by Django 5.1.5 on 2025-03-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ideafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
