# Generated by Django 5.1.5 on 2025-03-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_status_category_suggested_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='file',
        ),
    ]
