# Generated by Django 5.1.5 on 2025-04-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
