# Generated by Django 5.1.5 on 2025-04-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
